// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3PZ1UoY-QyewFbtPmGieO3KmCEkKwuI',
    appId: '1:67007923864:web:3b9dadd72fc1fab9de72ed',
    messagingSenderId: '67007923864',
    projectId: 'ctstransportapp',
    authDomain: 'ctstransportapp.firebaseapp.com',
    storageBucket: 'ctstransportapp.firebasestorage.app',
    measurementId: 'G-P4YYERXF1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_B80o_pJX6sPcKw75Zw7Q8sW5fP6O8XA',
    appId: '1:67007923864:android:0d57b9d174c999c7de72ed',
    messagingSenderId: '67007923864',
    projectId: 'ctstransportapp',
    storageBucket: 'ctstransportapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvOdrbu8YXrdtHwjt9MeBZ9eJk_AMYjOI',
    appId: '1:67007923864:ios:067c5510a8cc82c4de72ed',
    messagingSenderId: '67007923864',
    projectId: 'ctstransportapp',
    storageBucket: 'ctstransportapp.firebasestorage.app',
    iosBundleId: 'com.example.ctsTransportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvOdrbu8YXrdtHwjt9MeBZ9eJk_AMYjOI',
    appId: '1:67007923864:ios:067c5510a8cc82c4de72ed',
    messagingSenderId: '67007923864',
    projectId: 'ctstransportapp',
    storageBucket: 'ctstransportapp.firebasestorage.app',
    iosBundleId: 'com.example.ctsTransportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3PZ1UoY-QyewFbtPmGieO3KmCEkKwuI',
    appId: '1:67007923864:web:3b9dadd72fc1fab9de72ed',
    messagingSenderId: '67007923864',
    projectId: 'ctstransportapp',
    authDomain: 'ctstransportapp.firebaseapp.com',
    storageBucket: 'ctstransportapp.firebasestorage.app',
    measurementId: 'G-P4YYERXF1R',
  );
}
